[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "repospace"
dynamic = ["version"]
description = "A command line tool for managing multi-repository spaces"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.9"
authors = [{ name = "Nicolas Lebedenco", email = "nicolas@lebedenco.net" }]
keywords = ["cli", "repospace", "multi-repo", "manifest", "cmake"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = ["PyYAML>=6.0"]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.5.0",
    "gitlint-core >= 0.19.1",
    "black>=26.3.1",
    "nodeenv >= 1.10.0",
    "pytest>=7",
    "pytest-cov>=5"
]

[project.urls]
Homepage = "https://github.com/nlebedenco/repospace"

[project.scripts]
repospace = "repospace.app.main:main"

[tool.distutils.build]
build_base = ".build"

[tool.distutils.bdist_wheel]
dist_dir = ".dist"

[tool.distutils.sdist]
dist_dir = ".dist"

[tool.setuptools.dynamic]
version = { attr = "repospace.__version__" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
# Line length should match the setting in .editorconfig
line-length = 120

# Force exclude works like --exclude and --extended-exclude, but files and directories matching the
# regex will be excluded even when they are passed explicitly as arguments. This is useful when
# invoking Black programmatically on changed files, such as in a pre-commit hook or editor plugin.
#
# A regex preceded with ^/ will apply only to files and directories in the root of the project.
# '''
# (
#  ^/foo.py     # exclude a file named foo.py in the root of the project
#  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
# )
# '''
# Black uses a slash as separator even on Windows.
#
# NOTE: By default Black looks for pyproject.toml containing a [tool.black] section starting from
#       the common base directory of all files and directories passed on the command line. If it is
#       not there, it looks in parent directories. It stops looking when it finds the file, or a
#       .git file/directory, or a .hg file/directory, or the root of the file system, whichever
#       comes first.
#
#       Black constructs file paths relative to where it thinks the project root is, and only then
#       the paths are matched to the regex. For example,
#       `<PROJECT_ROOT>/external/foobar/scripts/make_bugs_pickle.py` is seen by Black as simply
#       `scripts/make_bugs_pickle.py` because the .git folder in `<PROJECT_ROOT>/external/foobar`
#       makes it believe the project root is the foobar folder. And contrary to what the
#       documentation seems to imply, passing `--config=<PROJECT_ROOT>/pyproject.toml` DOES NOT
#       affect the project root selected by Black, only the configuration file itself.
#
#       The workaround is to always pass a file from <PROJECT_ROOT> in the command-line so Black
#       finds <PROJECT_ROOT> as the common prefix path between all files. Then we only have to make
#       sure there is a force-exclude match for the dummy file. For example, assuming
#       `<PROJECT_ROOT>/pyproject.toml` is used as a dummy file we can enter from the project root
#       folder:
#
#           $ black --verbose --check pyproject.toml external/foobar/scripts/make_bugs_pickle.py
#
#       And this should produce an output similar to:
#
#           Identified `/devel/myproject` as project root containing a .git directory.
#           Using configuration from project root.
#           line_length: 120
#           force_exclude: (\.toml)|(/\.?external/.*)$
#           bootstrap ignored: matches the --force-exclude regular expression
#           external/foobar/scripts/make_bugs_pickle.py ignored: matches the --force-exclude regular expression
#           No Python files are present to be formatted. Nothing to do 😴
#
#      See https://github.com/psf/black/issues/3592
#
force-exclude = '(\.toml)|(/\.?external/.*)$'
