"""Generation of the repospace files consumed by CMake.

On every update, two files are (re)generated under ``<topdir>/.repospace/`` -- also when some member
failed, since the members that did move are on disk and their state is what these files describe:

  members.json    all resolved member data, flat, in resolution order
  packages.cmake  ENV{<package>_ROOT} defaults plus a stale-cache guard

Both files may appear in CMAKE_CONFIGURE_DEPENDS, so they are written with write-if-different
semantics: when the content is unchanged, the file is not touched at all — not even its timestamp.
When it changes, the write is atomic (temp file + rename). The guard hash covers the canonical
members.json bytes *and* the package roots derived from them, so any structural change (member
added, removed, moved, at a different commit, or activated/deactivated by a group filter)
invalidates existing CMake caches: whenever packages.cmake changes, so does the hash it carries.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import tempfile
from typing import List

from repospace import util
from repospace.manifest import QUAL_MANIFEST_REV, Manifest, ManifestMember

MEMBERS_JSON = "members.json"
PACKAGES_CMAKE = "packages.cmake"


def _cmake_quote(value: str) -> str:
    """Escape *value* for interpolation inside a quoted CMake string."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def _member_entry(member) -> dict:
    if isinstance(member, ManifestMember) or not member.is_cloned():
        sha = None
    else:
        try:
            sha = member.sha(QUAL_MANIFEST_REV, capture_stderr=True)
        except subprocess.CalledProcessError:
            sha = None
    return {
        "name": member.name,
        "path": member.path,
        "abspath": member.abspath,
        "url": member.url,
        "revision": member.revision,
        "sha": sha,
        "groups": list(member.groups),
        "cmake-packages": list(member.cmake_packages),
        "extension-commands": list(member.extension_commands),
        "declared-by": member.declared_by,
    }


def members_json_text(manifest: Manifest) -> str:
    data = {
        "version": 1,
        "topdir": manifest.topdir,
        "members": [_member_entry(member) for member in manifest.members],
    }
    return json.dumps(data, indent=2) + "\n"


def update_hash(members_text: str, roots_text: str = "") -> str:
    """Hash the repospace state the generated files describe.

    Both inputs matter: members.json alone misses a group-filter change that only rewrites the
    package roots, and the roots alone miss a member that merely moved to another commit.
    """
    digest = hashlib.sha256()
    digest.update(members_text.encode("utf-8"))
    digest.update(b"\0")
    digest.update(roots_text.encode("utf-8"))
    return digest.hexdigest()


def _guard_text(guard_hash: str) -> str:
    stale_message = (
        "The repospace changed since this build tree was configured (members added/removed/moved "
        "or at different commits). Re-configure from scratch: cmake --fresh (or delete "
        "CMakeCache.txt)."
    )
    lines: List[str] = [
        "# Generated by 'repospace update' -- do not edit.",
        "",
        f'set(REPOSPACE_UPDATE_HASH "{guard_hash}" CACHE STRING',
        '    "Repospace state at cache creation; detects stale CMake caches")',
        f'if(NOT REPOSPACE_UPDATE_HASH STREQUAL "{guard_hash}")',
        f'  message(FATAL_ERROR "{stale_message}")',
        "endif()",
    ]
    return "\n".join(lines) + "\n"


def package_roots_text(manifest: Manifest, warn=None, extra_filter=None) -> str:
    """Return the ENV{<package>_ROOT} part of packages.cmake.

    Generated apart from the guard block because it is what the guard hash must cover; see
    update_hash().
    """
    if manifest.topdir is None:
        raise ValueError("manifest has no topdir")
    lines: List[str] = []
    claimed = {}
    for member in manifest.members:
        # Inactive members are not cloned; their packages must neither get a root pointing at a
        # missing directory nor claim a package name away from an active member.
        if not manifest.is_active(member, extra_filter=extra_filter):
            continue
        for package in member.cmake_packages:
            owner = claimed.get(package)
            if owner is not None:
                if warn is not None:
                    warn(
                        f'CMake package "{package}" from member '
                        f"{member.name} is already provided by "
                        f"{owner.name}; first declaration wins"
                    )
                continue
            claimed[package] = member
            # posixpath, not abspath: backslashes are escape characters inside a quoted CMake
            # string. Quoting covers characters the topdir path may still contain; the package name
            # is restricted at validation because it cannot be quoted in the ENV{} position.
            root = _cmake_quote(member.posixpath)
            lines += [
                "",
                f"if (NOT DEFINED ENV{{{package}_ROOT}})",
                f'  set(ENV{{{package}_ROOT}} "{root}")',
                "endif()",
            ]
    return "\n".join(lines) + "\n" if lines else ""


def packages_cmake_text(manifest: Manifest, guard_hash: str, warn=None, extra_filter=None) -> str:
    """Return the complete packages.cmake text for *guard_hash*."""
    return _guard_text(guard_hash) + package_roots_text(
        manifest, warn=warn, extra_filter=extra_filter
    )


def write_if_different(path: str, text: str) -> bool:
    """Write *text* to *path* unless it already has exactly that content.

    Returns True if the file was written. An unchanged file is not opened for writing, preserving
    its timestamp for CMAKE_CONFIGURE_DEPENDS. Changed content is written atomically (temp file +
    rename).
    """
    data = text.encode("utf-8")
    try:
        with open(path, "rb") as f:
            if f.read() == data:
                return False
    except OSError:
        pass
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), prefix=os.path.basename(path) + ".")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
        # mkstemp creates the file 0600; give it ordinary umask-based permissions so other users
        # (CI, build services) can read it.
        umask = os.umask(0)
        os.umask(umask)
        os.chmod(tmp, 0o666 & ~umask)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise
    return True


def write_repospace_files(command, manifest: Manifest, extra_filter=None) -> None:
    """Generate members.json and packages.cmake for *manifest*."""
    rdir = os.path.join(manifest.topdir, util.REPOSPACE_DIR)
    os.makedirs(rdir, exist_ok=True)
    members_text = members_json_text(manifest)
    # The roots come first: the guard hash covers them, and generating them twice would repeat their
    # warnings.
    roots_text = package_roots_text(
        manifest,
        warn=getattr(command, "wrn", None),
        extra_filter=extra_filter,
    )
    cmake_text = _guard_text(update_hash(members_text, roots_text))
    cmake_text += roots_text
    write_if_different(os.path.join(rdir, MEMBERS_JSON), members_text)
    write_if_different(os.path.join(rdir, PACKAGES_CMAKE), cmake_text)
